name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.x
    - name: Publish .NET Core Project
      run: dotnet publish TicTacToe.csproj -c Release -o release --nologo
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: release/wwwroot
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Change base-tag in index.html from / to tictactoe-blazor
      run: sed -i 's/<base href="\/" \/>/<base href="\/tictactoe-blazor\/" \/>/g' release/wwwroot/index.html
